### ISSUE TITLE
Feedback on some items

### ISSUE THREAD

**Issue by HairyHog** [TheMysticSword/MysticsItems#102]
I like the ideas of most of the items and the designs and consistent look of them, but I feel the balancing of some of them could be changed.

Scratch Ticket - cool item, like this one a lot

Crystallised World - love the design of this and its effect, nice

Donut - almost completely pointless, may as well change it to every interactable or at least all forms of chests and barrels to giving health instead of just barrels, perhaps a short speed boost on using them could be good too.

Cup of Expresso - it's a green item yet with just one it's already worse than just one Energy Drink which is also a white item even if it's only when sprinting. Perhaps could be better if you gained less movement speed per chest and perhaps only 2 chests per stage BUT it is permanent and keeps stacking throughout the run. The sound it makes when adding a new stack is also both too loud and annoying, it's not really needed at all.

Mysterious Monolith - can see this easily breaking Captain with his hacking skill when used on Shrines of Chance if you have a lot of these and being able to stack multiple mountain shrines could also make it almost too useful. This seems much more like a red item than a green item even if the stat doesn't sound so major in just text.

Wirehack Wrench - I haven't tried this in multiplayer but I'm wondering if this breaks printers for other players too or just for the equipment user? If it's the former that would be pretty bad but I don't know.

**Comment by TheMysticSword** [comment]
Closing all suggestion/enhancement/balancing/feedback issues. A new, actual discussion board will be set up after the next mod update.

Thanks for the feedback though!
