### ISSUE TITLE
Treasure Map chests don't show up for clients in multiplayer

### ISSUE THREAD

**Issue by CubularMonoxide** [TheMysticSword/MysticsItems#103]
Unsure if clients carrying the item fixes this.

**Additional issue that I don't exactly know how to replicate:** I observed the Treasure Map capture zone clearing itself almost immediately as I entered it. It took about 1 second to fully charge. This was in Multiplayer, with a [PlayerBot](https://thunderstore.io/package/Meledy/PlayerBots/) carrying the first instance of the item. However, the issue persisted even when I picked up my own copy of the item at a later point in the run.

**Comment by TheMysticSword** [comment]
The zone clearing immediately is a mistake on my end - I set the required time to 1 second when fixing bugs related to this item, but forgot to undo that change afterwards.

**Comment by TheMysticSword** [comment]
Finally fixed!
