### ISSUE TITLE
Scratch Ticket seems to also affect the drop rate of Elite Aspects (tested using ZetAspects mod, but the issue should appear with vanilla aspects aswell since all the mod does is change the values of the already existing items) (this might also affect other drop rates, but I haven't tested this).

### ISSUE THREAD

**Issue by GitHub6F3C3C** [TheMysticSword/MysticsItems#115]

**Comment by GitHub6F3C3C** [comment]
Upon further testing (finding a Scratch Ticket 3D printer) I can confirm it does indeed raise drop chance by 1% per stack. At 50 scratch tickets, one elite enemy out of two drops their aspect.

**Comment by TheMysticSword** [comment]
Yeah, that's intended. The item increases *all* chance-based effects that can be attributed to the owner, and the probability of an elite aspect dropping is attributed to the killer. Same with the vanilla Clover.

**Comment by TheMysticSword** [comment]
Actually, that might not be a good thing since even one stack gives you an entire 1% chance to get an elite aspect. I'll think about this.

**Comment by TheMysticSword** [comment]
Fixed with 9a9a0ef2397e0e328676bd89c5306ebc85e71e74
