### ISSUE TITLE
Shrine of Chance Gives No Items

### ISSUE THREAD

**Issue by drp527** [TheMysticSword/MysticsItems#12]
I'm pretty sure this isn't just a luck thing because I've failed upwards of 23 rolls across 3 shrines. It could be, but seems unlikely. Restarted games until I had a shrine on stage 1, farmed up money, and threw it at shrines until I gave up. Maybe a mod compatibility thing but with just this mod disabled everything seems to work fine. Log here if it helps: [https://cdn.discordapp.com/attachments/384286301077241867/818903624863318106/LogOutput.log](url)

**Comment by Azzezima** [comment]
Same thing here.

**Comment by drp527** [comment]
I just noticed that there's already two reports of this in closed issues and that it's been fixed internally. Closing this myself now.
