### ISSUE TITLE
[Balancing] My personal feedback on the items

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [TheMysticSword/MysticsItems#120]
First off, props to you for making a highly polished item pack which fits almost seamlessly into the base game. I've played around with all of the items on several runs, and I think most of them are properly balanced, but here're my thoughts on some in particular:

**Faulty Spotter** - In a perfect world, this would be an actual drone you could repair, and not an item. ChensGradiusMod added new drones to the game in the past, maybe you could look into that if you wanted to expand upon this idea. You could re-use the same model you placed in Sundered Grove. As for the item, the fact the amount of scanned enemies is the value that stacks makes it very earrape-y once you go past several stacks. Maybe lower the initial critical chance, and let that scale instead?

**Relentless Vendetta** - It could really use shorter durations. It often feels like the effect is on at all times. With 15 seconds base and 15 additional seconds per stack you can very easily achieve constant Vendetta status once a single one of your drones dies during the Mithrix fight, using 3D printers or cauldrons. I would put it at 12 seconds base and 8 additional seconds per stack (exactly double the values of Berserker's Pauldron).

**Mysterious Monolith** - This item seems really out of place in the "normal" item pool, both balance-wise aswell as aesthetics-wise. It's very easily abusable when it comes to shrines of chance, but it also leads to very awkward moments where extremely expensive shrines of chance will never be deplenished. Shrines of the mountain do not spawn as reliably as the former, making extra teleporter rewards a very rare scenario where you happen to have Monoliths in your inventory and also found a shrine. From my experience, it seems like a very chaotic item. For that reason I think it would fit best into the Lunar tier, making it akin to Defiant Gouge (which spawns enemies on shrine usage, and does nothing else). You could add a downside, but for me it already has a very high risk/reward level (which thematically fits with both the game and the concept of lunar items), as you'll be potentially wasting lots of precious time trying to scrounge the last white out of a shrine of chance or struggling against elite superbosses because of multiple challenges of the mountain. Not to mention an ominous, black monolith doesn't belong with the other bits and baubles, but looks more like a unique artifact (which could reminisce the Obelisk where you can choose to obliterate).

**Treasure Map** - A very fun item, and well balanced, asking you to commit time and effort into a random Red. The only suggestion I could give is multiplayer related, to maybe have the area charge faster if more players are inside, just like teleporters. Maybe even have it act as a "Holdout Zone", and let the items that affect them (Lepton Lily, Focused Convergence, Crystallized World) work on the treasure spot too.

**Rift Lens** - As of right now this item is essentially a must-buy, since a single Red Whip negates its downside. I suggest for it to add +33% movement speed penalty per stack, and for each 33% penalty to be removed one at a time as you get rid of the Rift Afflictions by opening the chests (rather than having to open all of them).

**Gate Chalice** - A very interesting item. Love the visual effect, makes it seem like you're doing something you're not supposed to do. I think the debuffs should be a bit more emphasized since they become trivial in later stages (maybe have them scale better with player power, somehow). The cooldown should comfortably be raised to something like 3-5 minutes, balancing it out once you start stacking Fuel Cells. It also should not be usable in Commencement (where it just reloads the stage) to avoid issues/trolling/cheesing.

**Ratio Equalizer** - Incredible potential. Its cooldown should be inbetween the older value and the newer one, 30 seconds would be ideal. Mithrix being affected by this is very, very wrong. Attempting to use it on him should result in a cool easter egg (or very bad outcome) rather than its intended purpose.

Again, very nicely done with this. Good luck on your work.

**Comment by TheMysticSword** [comment]
Closing all suggestion/enhancement/balancing/feedback issues. A new, actual discussion board will be set up after the next mod update.

Thank you for the feedback though!
