### ISSUE TITLE
Vintage Microphone Lag

### ISSUE THREAD

**Issue by DarkInsignia** [TheMysticSword/MysticsItems#125]
Using the Vintage Microphone destroys my FPS, making the game lag for at least 3 seconds. I am not sure why this happens, my PC is good enough (intel i7 4770, gtx 1070, 16GB RAM)

**Comment by TheMysticSword** [comment]
Are you sure that it's lag and it's not just you getting knocked around by the projectiles? I broke something and now the projectiles actually collide with entities, which can cause choppy camera movement because you're being instantly moved by a few units.

**Comment by DarkInsignia** [comment]
Hi, I am certain it was lag. I'll try to record it for you the next time I play risk of rain. Cheers.

**Comment by TheMysticSword** [comment]
I have just uploaded a patch to Thunderstore that has a few code changes to Vintage Microphone. Update the mod and let me know if this issue is still present or if we can close it.

**Comment by DarkInsignia** [comment]
Hey, I checked it and it got fixed. Cheers!
