### ISSUE TITLE
Error Loading Mod 

### ISSUE THREAD

**Issue by BigDopa** [TheMysticSword/MysticsItems#126]
Got an error while trying to load the mod with the R2modman launcher 

KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
MonoMod.Cil.ILCursor.GotoNext (MonoMod.Cil.MoveType moveType, System.Func`2[Mono.Cecil.Cil.Instruction,System.Boolean][] predicates) (at <9218caa36358471fb3c33e4432ee554c>:IL_000A)
MonoMod.Cil.ILCursor.GotoNext (System.Func`2[Mono.Cecil.Cil.Instruction,System.Boolean][] predicates) (at <9218caa36358471fb3c33e4432ee554c>:IL_0000)
ItemTweaks.Tweaks.ArmorPlates+<>c__DisplayClass0_0.<ChangeItem>b__0 (MonoMod.Cil.ILContext il) (at <cf35fde2e4394a6a956e7b31a513c5e6>:IL_0008)
MonoMod.Cil.ILContext.Invoke (MonoMod.Cil.ILContext+Manipulator manip) (at <9218caa36358471fb3c33e4432ee554c>:IL_0087)
MonoMod.RuntimeDetour.ILHook+Context.InvokeManipulator (Mono.Cecil.MethodDefinition def, MonoMod.Cil.ILContext+Manipulator cb) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_0012)
DMD<Refresh>?29928192._MonoMod_RuntimeDetour_ILHook+Context::Refresh (MonoMod.RuntimeDetour.ILHook+Context this) (at <2d5fc8aa2f894a5483cc42818475eec9>:IL_00EA)
DMD<>?29928192.Trampoline<MonoMod.RuntimeDetour.ILHook+Context::Refresh>?884197376 (System.Object ) (at <9ab49050ec7b4a8caf82deb75238ac77>:IL_0020)
HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (System.Object self) (at <c24093a882714adc80ea816abe5f1891>:IL_0000)
MonoMod.RuntimeDetour.ILHook.Apply () (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_0059)
MonoMod.RuntimeDetour.ILHook..ctor (System.Reflection.MethodBase from, MonoMod.Cil.ILContext+Manipulator manipulator, MonoMod.RuntimeDetour.ILHookConfig& config) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_0140)
MonoMod.RuntimeDetour.ILHook..ctor (System.Reflection.MethodBase from, MonoMod.Cil.ILContext+Manipulator manipulator, MonoMod.RuntimeDetour.ILHookConfig config) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_0000)
MonoMod.RuntimeDetour.ILHook..ctor (System.Reflection.MethodBase from, MonoMod.Cil.ILContext+Manipulator manipulator) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_001C)
MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook (System.Reflection.MethodBase from, MonoMod.Cil.ILContext+Manipulator to) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_0000)
MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate] (System.Func`3[T1,T2,TResult] gen, TDelegate hookDelegate) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_003C)
MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify (System.Delegate hookDelegate) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_0013)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify (System.Reflection.MethodBase method, System.Delegate callback) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_0028)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T] (System.Reflection.MethodBase method, System.Delegate callback) (at <d9e9f28db1e84055befcfc31c0c2d253>:IL_0000)
IL.RoR2.HealthComponent.add_TakeDamage (MonoMod.Cil.ILContext+Manipulator ) (at <e4c2065d957a4bb3a81173cdebdb9527>:IL_000A)
ItemTweaks.Tweaks.ArmorPlates.ChangeItem () (at <cf35fde2e4394a6a956e7b31a513c5e6>:IL_0212)
ItemTweaks.ItemTweaks.Awake () (at <cf35fde2e4394a6a956e7b31a513c5e6>:IL_0008)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

**Comment by TheMysticSword** [comment]
It's a bug with ItemTweaks, unfortunately I can't do anything about this.
