### ISSUE TITLE
Spotter Drone / Huntress Flurry interaction

### ISSUE THREAD

**Issue by gaforb** [TheMysticSword/MysticsItems#137]
The shots against spotter'd targets still take critical damage, but huntress will only fire 3 shots

**Comment by TheMysticSword** [comment]
Not technically a bug, since Flurry fires 6 arrows if a crit is *rolled* and not *dealt*, but that's not clarified in the game, so from a player's perspective it is a bug. I will add support for this interaction though - seems easy to do.
