### ISSUE TITLE
The green tiered expresso Item doesnt show a change in the rate of fire and movement speed.

### ISSUE THREAD

**Issue by WingAlchemist** [TheMysticSword/MysticsItems#14]
It doesnt seem to make any changes in the number value of the movement or attack speed of a survivor while using the mod BetterUI By XoXFaby. So its very hard to tell really if it is having an effect or not as I couldnt really tell any difference with the movement speed really let alone the attack speed either. Anyway, besides that I havent found anything yet but keep the good work up. I can see this mod going places and I love the idea of survivor specific items

**Comment by TheMysticSword** [comment]
Fixed with b862628c96c15de6f2361f34a35e83eae53eee06
