### ISSUE TITLE
issue when joining friends incompatible version types 

### ISSUE THREAD

**Issue by jonsor1** [TheMysticSword/MysticsItems#151]
when joining friends you get disconnected from the host with the message 
'==incompatible mods==com.themysticsword.mysticitems;1.1.12' 
'==incompatible mods==com.themysticsword.mysticitems;1.1.10'
 we all use the r2mod manager and  have used the same code to download the mod profile, we are currently all running the 1.1.10 version as even when every member including the host is on 1.1.12 the error occurs. it has only started happening since the 1.1.12  update

**Comment by TheMysticSword** [comment]
This shouldn't happen anymore starting from mod version 2.0.13
