### ISSUE TITLE
Void Fields Balancing - Relentless Vendetta and Scratch Ticket

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [TheMysticSword/MysticsItems#152]
In its new state, Relentless Vendetta gives a 100% bonus to damage and attack speed to all spawned enemies for 24 seconds. In other words infinitely as long as the player doesn't just run in circles and not kill a single mob. This can't always be managed. But the point is that the bonuses given are too great for them to feel balanced with what other green items enemies can obtain. I suggest either simply blacklisting Relentless Vendetta from enemies, OR adding a minimum distance (...after a death of an ally within 25m). 

On the topic of blacklist, I think Scratch Ticket is in it? Because I've never seen it come up in any of my runs unlike Spine Implant. Unless you've tested it and there were issues, I think it would be more than balanced to include it in the enemy's item pool, synergizing well with others like ATG or Ukulele without being too ridiculous.

**Comment by TheMysticSword** [comment]
I think Relentless Vendetta is fine because Void Fields are supposed to be the "high risk - high reward" secret location. Scratch Ticket doesn't appear, that's true - I forgot to unban it from enemies when it got reworked.

**Comment by TheMysticSword** [comment]
Closing all suggestion/enhancement/balancing/feedback issues. A new, actual discussion board will be set up after the next mod update.

I'm still okay with Vendetta being allowed on enemies, but you can use the AI Blacklist mod by Moffein to configure that https://thunderstore.io/package/Moffein/AI_Blacklist/
