### ISSUE TITLE
Suggestion: Scratch Ticket changes

### ISSUE THREAD

**Issue by gaforb** [TheMysticSword/MysticsItems#153]
Rather than scratch tickets boosting your odds by 1% flat, I think they could instead increase them by 10% of the original chance per stack. This would allow them to affect <1% chances, retain their current scaling for items like ATG, and make them more dynamically effective for things like critical chance and bleed. For balancing you could also make this scale with diminishing returns, similar to tougher times.
Speaking of tougher times, does this item work on it? Since it's "unaffected by luck" I think having scratch ticket be unable to affect it would also make sense. (and prevent the survivor from becoming 100% immune to damage)

Code wise, I think replacing 
`percentChance += 1f + 1f * (itemCount - 1);`
with
`percentChance *= 1f + (0.1f * itemCount);`
would achieve the desired effect.

**Comment by TheMysticSword** [comment]
Closing all suggestion/enhancement/balancing/feedback issues. A new, actual discussion board will be set up after the next mod update.

I'm not really happy with this kind of change - it would become even more of a Clover-like, whereas a flat +1% is a pretty unique effect that isn't present in any item. But I'll add this kind of scaling as a config option.
