### ISSUE TITLE
Cup of Expresso buffs shouldn't be removed by losing items

### ISSUE THREAD

**Issue by TheMysticSword** [TheMysticSword/MysticsItems#164]

**Comment by gaforb** [comment]
Personally disagree with this one - prevents using a 3d printer to gain max expresso buffs with no looting, for example.

**Comment by TheMysticSword** [comment]
> Personally disagree with this one - prevents using a 3d printer to gain max expresso buffs with no looting, for example.

That's why I made it take away the buffs in the first place. On the other hand, there are instances where taking buffs away is weird:
* Mithrix's 4th phase - when he steals the cup, you lose all buffs and he gets the full buff. But each time you get an item back, he loses the stacks, which makes it useful for him only for the first 5-10 seconds of the fight. Also, the only way to get the buff stacks on Commencement is to use a cauldron, which can be risky if you don't have spare scrap, and is really disappointing when you risk messing up your build only for the buff stacks to be removed later.
* Forgotten Haven - with that mod, you can find a yellow Relic of Energy item on the stage. That thing is used for activating the Broken Teleporter, which *consumes* the Relic, taking away your buff stacks since technically you lost the item. Also, in the stage, you need to power a special teleporter with Fuel Cells in order to leave, which also counts as losing an item.

**Comment by gaforb** [comment]
Would it be possible to tie it to actually interacting with the 3d printer or scrapper, rather than losing the item?

**Comment by TheMysticSword** [comment]
It probably is possible, but that's too much effort for essentially making the item worse under niche circumstances. Also, if it *did* remove stacks when printing, then you would lose all of your stacks if you loot everything first and print after, and that's just bad. It's better to just scrap the stack-removing mechanic entirely.
