### ISSUE TITLE
Ratio Equalizer gave me infinite health. I have no idea how

### ISSUE THREAD

**Issue by Dexterity10** [TheMysticSword/MysticsItems#170]
![image_2021-07-27_181333](https://user-images.githubusercontent.com/87932931/127262623-351f5e2a-fc14-4b56-9b60-0d5e603cce4e.png)

I'm not sure how this happened. All I know is that there is now a parent that is invincible, and so am I. Everything else around us two are killable and working fine, just me and that one parent

might have something to do with the Transcendence, but I'm not sure

Update: going to the next stage reset my health to the actual numbered amount. Everything seems to be working fine now

**Comment by TheMysticSword** [comment]
The item functions differently now by setting everyone's health fraction equal to yours, so no divison errors should happen anymore. Haven't received any reports of this ever since.
