### ISSUE TITLE
Faulty Spotter Issues

### ISSUE THREAD

**Issue by gaforb** [TheMysticSword/MysticsItems#178]
I killed a pillaging elite that had one and the debuff never went away
Also, the debuff can't be removed by Blast Shower
Also, it should probably just be AI blacklisted

**Comment by TheMysticSword** [comment]
The bug was probably due to me accidentally removing the timed debuff twice and causing the debuff counter to become -1 instead of 0, which I fixed a few versions ago. Most likely fixed at this point, since I haven't gotten this bug ever since, and nobody else has been reporting it now.
