### ISSUE TITLE
Lunar Icon Outlines are off-model

### ISSUE THREAD

**Issue by gaforb** [TheMysticSword/MysticsItems#179]
They're dark blue, when they ought to be cyan - see this screenshot for comparison.
![image](https://user-images.githubusercontent.com/38703458/128632978-fc601c18-3439-4728-963f-a9c68ce8fc16.png)
Also there's now a mod by Kevin that lets you generate outlines in-game, if that's easier than the method you used for the other items. https://thunderstore.io/package/KevinfromHPCustomerService/PickupIconRenderer/

**Comment by TheMysticSword** [comment]
Thanks, I never noticed that! Fixed in the upcoming update.
