### ISSUE TITLE
Suggestion: Slight change to the thought processor

### ISSUE THREAD

**Issue by SammySemicolon** [TheMysticSword/MysticsItems#184]
It'd be really awesome if the thought processor worked based off of ability index rather than ability type.
Being in multi's power mode and having your left click recharge your right click and the opposite would be amazing <3

**Comment by TheMysticSword** [comment]
This was a good suggestion, but unfortunately it won't be done, because the item is getting a total rework in the next update. It felt weird to have an Alien Head sidegrade in the same tier pool as Alien Head itself.
