### ISSUE TITLE
[Suggestions] A few rebalance notes

### ISSUE THREAD

**Issue by HR-UP** [TheMysticSword/MysticsItems#186]
Hi.
The baseline difficulty for all suggestions below is Eclispse 7-8.

DONUT: is really weak and considered useless in 99% of the time, it would better be a:

a) 30-50% of max hp heal for each item and it should be applied over great period of time (20-30 seconds), while each additional stack gives a boost in heal duration, not strenght. A steep increase in heal is due to scarce pickup ratio comparable to just plain constant heal over time from a Slug or something similar. 

b) 20-30% instant heal, but overheal will be applied to a temporary move speed boost with good convertion rate like 5-7 hp is 1 sec of 20% speed boost or something.

SPINE IMPLANT: should be buffed to 15-20 armor each since you catch damage with your face more ofen then with your back, but current 10 armor for "half" of your mesh assumes it's 50/50.

CONTRABAND GUNPOWDER: % chance of getting it from kill should be increased a bit to 15-18%, also stored gunpowder charge do not just aoe immediately around you, but instead be stack and applied to next hit a player does to an enemy, because 70%+ of charge explode to no effect, rendering this item nearly useless, but it can be really good with changes above in synergy with vanilla Monster Tooth item.

WIREHACK WRENCH: behaves sometimes really strange, not detecting a printer nearby, and sometimes detecting it only under some wierd X and/or Y angles, most of the times works just fine.

**Comment by TheMysticSword** [comment]
Closing all suggestion/enhancement/balancing/feedback issues. A new, actual discussion board will be set up after the next mod update.

Thank you for the feedback! I'm improving Spine Implant and Contraband Gunpowder in the next update, and adding a config so you can tweak the Donut's values if you feel that they're too low.
