### ISSUE TITLE
More config options (Enhancement)

### ISSUE THREAD

**Issue by ExtremeNinja777** [TheMysticSword/MysticsItems#189]
I think one thing that would be nice as a enhancement to the mod would be adding more config options, like changing the values on the items, for example: the player can change in the config how long you need to stand in the treasure map X to excavate the legendary chest, how it stacks, etc. That way players can balance the modded items however they want, whether they want to make things even more broken or nerf them as they wish.

**Comment by TheMysticSword** [comment]
Closing all suggestion/enhancement/balancing/feedback issues. A new, actual discussion board will be set up after the next mod update.

Took me an entire year since release to finally agree to make a config 😅 Doing it in the next update!
