### ISSUE TITLE
Multiplayer issue 

### ISSUE THREAD

**Issue by CMadigan1998** [TheMysticSword/MysticsItems#190]
Me and my friend have been having an issue with mystic Items mod since the 1.1.13 update. When we try and join one another multiplayer session we get kicked because of the mystic items mod. The Message we get is "incompatible mod. Host has mystic items version 1.1.12 but you have mystic items 1.1.13" We try and downgrade to an older version of the game but we still get the same error message with the same version. Has anyone else experience this error? Is there anyway we can fix it?

**Comment by TheMysticSword** [comment]
Hi! Could both of you please try opening your `BepInEx` folder and deleting the `cache` folder inside it?
(If you're using r2modman or Thunderstore Mod Manager, go to Settings > Browse profile folder, from there you can find the BepInEx folder)

**Comment by TheMysticSword** [comment]
This should no longer happen starting from mod version 2.0.13
