### ISSUE TITLE
game is not starting

### ISSUE THREAD

**Issue by ryderkill** [TheMysticSword/MysticsItems#199]
[Error  : Unity Log] MissingMethodException: void MysticsRisky2Utils.BaseAssetTypes.BaseItemLike.SetAssets(string)
Stack trace:
MysticsRisky2Utils.BaseAssetTypes.BaseEquipment.Load () (at <dad1b436dd954bbdbfcc93d63c9dc2d3>:IL_000C)
MysticsRisky2Utils.ContentManagement.ContentLoadHelper+AsyncLoadingEnumerator`1[OutType].System.Collections.IEnumerator.MoveNext () (at <dad1b436dd954bbdbfcc93d63c9dc2d3>:IL_0035)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <e6a10261304544b28d600f4ad48b78df>:IL_007F)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <e6a10261304544b28d600f4ad48b78df>:IL_0000)
EliteVariety.EliteVarietyContent+<LoadStaticContentAsync>d__2.MoveNext () (at <fdf98ef59bc54e589595a23c8fe83823>:IL_0207)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <e6a10261304544b28d600f4ad48b78df>:IL_007F)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <e6a10261304544b28d600f4ad48b78df>:IL_0000)
RoR2.RoR2Application+<LoadGameContent>d__61.MoveNext () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0161)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2cc17dca390941eeb4d7b2ff1f84696a>:IL_0027)****

help

**Comment by TheMysticSword** [comment]
You are using Elite Variety, which is no longer maintained by me and was bound to break with MysticsRisky2Utils 2.0 update. You can either disable it, or disable Mystic's Items and downgrade Utils to the previous version.
