### ISSUE TITLE
Chaos Artifact and Gunpowder

### ISSUE THREAD

**Issue by Appletwice** [TheMysticSword/MysticsItems#201]
You can damage yourself by picking contraband gunpowder, I don't know if it's intended but if it is, then it's not a very good item, especially because most of vanilla items are blocked from doing so

**Comment by TheMysticSword** [comment]
All AoE explosive attacks deal damage to friendlies with Chaos, including Gasoline and Will-o'-the-Wisp. It's not really something I can change

**Comment by TheMysticSword** [comment]
Okay, someone actually told me you *can* make explosions not affect yourself with Chaos, so I'm reopening this until the next bugfix.
