### ISSUE TITLE
Marwan's ash upgraded forms increasing enemies max up instead of dealing damage.

### ISSUE THREAD

**Issue by DefNotZeke** [TheMysticSword/MysticsItems#207]
I'm not sure how to post the log but I've tested this by only picking up marwans ash and diary's to level up quickly and I noticed that the damage over time effect wasn't happening on basic enemies. After testing it versus bosses I could see that every few seconds the bosses max up would increase after getting hit while holding the marwan's ash's 2nd and 3rd forms.

**Comment by TheMysticSword** [comment]
Not sure why it didn't proc the DoT on regular enemies, but bosses gaining max hp is not a bug - that's how enemy stats actually work in the game. Their stats change every second based on the difficulty timer, not every level like how it works with players.
