### ISSUE TITLE
Can't obtain the Logbook entries for Marwan's Ash upgrades

### ISSUE THREAD

**Issue by ArcaneTxsa** [TheMysticSword/MysticsItems#224]
The upgraded versions of Marwan's Ash have their own entries in the logbook, however they remain locked even when you upgrade the ash. I don't know if there's any convenient way to fix it, and it isn't a major issue so should for sure be at the bottom of priority, just wanted to bring it up :)

**Comment by TheMysticSword** [comment]
Fixed in 2.0.9!
