### ISSUE TITLE
Items  turning into "MissingNo"

### ISSUE THREAD

**Issue by TheReaperWolf** [TheMysticSword/MysticsItems#228]
Did some test runs of a modpack im working on, after picking up any modded item it would turn into what i could best describe as a "missingno" with 20 stacks, any item picked up afterwards seems to meet the same fate.

This Issue stopped happening after disabling MysticsItems, which is why i believe the latest update might have broken something.
This should probably be looked into and fixed.

Anyways have a great Day and Weekend

**Comment by TheMysticSword** [comment]
Fixed in 2.0.8!
