### ISSUE TITLE
Game stops loading after reaching mod.

### ISSUE THREAD

**Issue by D00medCells** [TheMysticSword/MysticsItems#233]
[Error: Unity Log] MissingFieldException: Field 'RoR2.ItemDef.tier' not found.
Stack trace:
MysticsRisky2Utils.BaseAssetTypes.BaseItem.Load () (at <d4094782784f43e2aa2d463a13c5202e>:0)
MysticsRisky2Utils.ContentManagement.ContentLoadHelper+AsyncLoadingEnumerator`1[OutType].System.Collections.IEnumerator.MoveNext () (at <d4094782784f43e2aa2d463a13c5202e>:0)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <af35e5d66a1c460ab7a98204d8b582d2>:0)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <af35e5d66a1c460ab7a98204d8b582d2>:0)
MysticsItems.MysticsItemsContent+<LoadStaticContentAsync>d__2.MoveNext () (at <61ba1e1a58f74cc4a7106c92c6cf823f>:0)
HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <af35e5d66a1c460ab7a98204d8b582d2>:0)
HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <af35e5d66a1c460ab7a98204d8b582d2>:0)
RoR2.RoR2Application+<LoadGameContent>d__70.MoveNext () (at <7a5120bd69d843a8b8e90b8cce404663>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <469e86e97fa2467ebffe49bbd6086325>:0)

The game can't load when I enable the mod, I've also been having issues with other item mods but turned everything else off when testing.

**Comment by Oridjinn1980** [comment]
Chiming in to say it's doing the same for me! Game launches, but the progress bar will never finish loading. Once I disable this mod and the MysticsRisky2Utils mod, it loads fine and everything works as normal.
