### ISSUE TITLE
Light show with Marwan's light.

### ISSUE THREAD

**Issue by Sporeshroom42** [TheMysticSword/MysticsItems#235]
Hello, i'm really enjoying your mod but i got an issue. I don't really know to who i need to address it but i hope you can deal with that, or notify other authors on how to fix it.
Modded enemies that are hit with Marwan's light become a rave show. Specifically large enemies? Not sure.
Hitting Frost wisps. (Forgotten Relics)
![image](https://user-images.githubusercontent.com/43946668/167026050-cb1bde99-c330-48c1-9403-ace4b6548132.png)
Hitting Sigma constructs. (Spikestrip)
![image](https://user-images.githubusercontent.com/43946668/167026098-a412725c-3763-4f3d-90af-355b98c2fb5e.png)
Log if needed:
[LogOutput.log](https://github.com/TheMysticSword/MysticsItems/files/8636071/LogOutput.log)

**Comment by TheMysticSword** [comment]
I've tried, but it doesn't seem like it's something I can fix.

**Comment by Sporeshroom42** [comment]
Oh well, should I tell other mod developers then? Maybe they can fix it on their end?
