### ISSUE TITLE
Configs don't work

### ISSUE THREAD

**Issue by SirTinyHead** [TheMysticSword/MysticsItems#236]
After the latest patch all configs I made on mystics items have no effect anymore. This affects all 3 configs including disabled items, balance changes, and general changes.

**Comment by TheMysticSword** [comment]
The Content Toggle config was intentionally removed in the latest patch, and all of its options were moved into the General config under "Enabled Items" and "Enabled Equipment" sections.
Balance config now requires you to set the "Ignore Balance Config" option at the top of the file to "false".
Are you sure that the General config is not working though?

**Comment by TheMysticSword** [comment]
Oh, I'm looking into it right now, and seems like disabling items and equipment doesn't remove it from the logbook, despite properly working during testing.
