### ISSUE TITLE
[Compatibility "TinkersSatchel"] Giving Marwan's light to an Item Drone is gamebreaking and causes huge FPS drop.

### ISSUE THREAD

**Issue by MichalGolaszewski** [TheMysticSword/MysticsItems#241]
One of the addons of [TinkersSatchel mod](https://github.com/ThinkInvis/RoR2-TinkersSatchel) is the Item Drone, which is basically an equivalent of the Equipment Drone for passive items. Giving an item to the drone grants the effects of the passive item to all allies in the area, so it affects other drones.

Last run I gave 5 stacks of Marwan's Light to the drone and it essentially broke the game, the damage from the item became weirdly high on the drones (up to several thousands, refer to screenshot) and the game started freezing (around 0.5 fps)

![marwanBug](https://user-images.githubusercontent.com/46850235/170646754-58d1f28d-fb30-4671-a5aa-5fe4f1eafeff.png)

**Comment by TheMysticSword** [comment]
Huh. I swear I blacklisted all of Marwan's Ash versions from TILER2-dependent mods, but I guess that's not the case :(

**Comment by TheMysticSword** [comment]
Oh, found the issue. Looks like I banned only Marwan's Ash and not the upgraded versions 🙃
