### ISSUE TITLE
Legendary Mask "attachment" twitches rapidly on Void Fiend

### ISSUE THREAD

**Issue by RhapsodySL** [TheMysticSword/MysticsItems#254]
When on Void Fiend the Legendary Mask body attachment appears to twitch rapidly, in accordance to how much corruption the Void Fiend has (wherein the more corruption it has, the more violently it twitches). Presumably this isn't intentional, and it's rather distracting.

**Comment by TheMysticSword** [comment]
Void Fiend's whole body naturally twitches the more corruption it has, that's vanilla behaviour. But it's definitely not intended to be distracting. I'll see what I can do about this. Probably just going to turn off the flame particles when it's worn by Void Fiend.

**Comment by RhapsodySL** [comment]
> Void Fiend's whole body naturally twitches the more corruption it has, that's vanilla behaviour. But it's definitely not intended to be distracting. I'll see what I can do about this. Probably just going to turn off the flame particles when it's worn by Void Fiend.

For what it's worth I'm not talking about how Void Fiend twitches, but rather how the Legendary Mask (which isn't physically attached to the body, but follows Void Fiend's twitching anyway) twitches.

**Comment by TheMysticSword** [comment]
Oh wait it's not even attached to the body? It's supposed to be following its head. I'll take a look at this later this week.

**Comment by RhapsodySL** [comment]
Yeah, it was trailing behind it, to the a bit I think?

**Comment by TheMysticSword** [comment]
Jeez, yeah, this is NOT intended. I wonder why nobody reported this before lol
![image](https://user-images.githubusercontent.com/26709843/197446564-2391dc1c-5a48-4b69-86a8-d40c11b5f92e.png)
