### ISSUE TITLE
Time dilatior effect persists while in void fields after enemiy dies

### ISSUE THREAD

**Issue by clstr** [TheMysticSword/MysticsItems#265]
If an enemy gets Time Dialator the effect works, but once they die the debuff never goes away.

![image](https://user-images.githubusercontent.com/1195526/209581836-12aff4fb-cc74-42a3-9b16-e2d35bed8641.png)

**Comment by TheMysticSword** [comment]
Fixed in 2.1.1, thanks for the report!
