### ISSUE TITLE
Marwan Ash's Burn stacks/ramps damage on multiple hits

### ISSUE THREAD

**Issue by Justfines** [TheMysticSword/MysticsItems#273]
I noticed when experimenting with the items, that Marwan's Ashes upgrade 2 and 3 seems to increase in damage based on how many times the enemy gets hit, even though everything points to that not supposed to be happening. (DoT icon implies its non-stacking etc) 

This was really noticeable with rapid fire (eg multi-t's nail gun) even with a single stack of the item.

This is with mod version 2.1.4,

**Comment by TheMysticSword** [comment]
Thanks for the report! Was wondering why my damage suddenly spiked at one point in a run. Fixed in 2.1.5!
