### ISSUE TITLE
Black Monolith doesn't work

### ISSUE THREAD

**Issue by Vallith** [TheMysticSword/MysticsItems#277]
This item doesn't seem to work at all - I picked it up on a stage and it let me use already used shrines once more, but then that was it. Shrines I hadn't used fully didn't get another shot, and going forward a shrine never gave me more than it's usual amount of tries.

**Comment by Darkmega18** [comment]
I have this also.
I seem to notice a small monolith similar to the item on the ground always next to all the shrines. but even the couple times I got the item I was unable to trigger it or the shrine I used another time afterwards.

**Comment by XaniusNorarte** [comment]
it seems like the black monolith works on the first run after just launching the game for me, but the run after the first it stops working.

**Comment by Darkmega18** [comment]
beautiful. :D looking forward to being able to use this soon then?

**Comment by TheMysticSword** [comment]
Yep! It's live now!

**Comment by Darkmega18** [comment]
I saw when I just went into thunderstore. thanks a lot. :D
