### ISSUE TITLE
Rifts on the fritz after last update.

### ISSUE THREAD

**Issue by Darkmega18** [TheMysticSword/MysticsItems#279]
seems the mystic items update just broke the rifts.

Suddenly the unstable rifts which were mostly passive last update became extremely hyper active and are spawning electrical explosions every frame. they vaporize you the moment you step in range. and sometimes I'll spawn into a level and only get given like 10 seconds to collect everything and die instantly like I had happen in this video before the update.

https://www.youtube.com/watch?v=gOzju28wTq0

I'm unsure if it's due to the chocolate chip cookies reducing a buff effect or maybe the hourglass green item from bubbets that increases buff durations by a percentage or if it's something else I might randomly pick up that breaks them.

**Comment by Darkmega18** [comment]
not just invisible. completely impenetrable clusters of permafreezing instant death... I hope it covers that. they literally barf out projectiles at game lagging speeds and even with a portable reactor giving me complete invulnerability for 80 seconds or so at the start of the level I approach the rifts and I'm practically permanently frozen and it stales me out long enough that I just die to the timer running out instead.

**Comment by TheMysticSword** [comment]
The projectiles also include three Artificer Snapfreeze pillars around each rift, and, well, the projectiles themselves were invisible because of error spam each frame, which should be fixed in the latest version. I think it should be all fine now. Also, I think I found the culprit of the 10-second-timer bug too, so that should be fixed as well!

**Comment by Darkmega18** [comment]
so it's meant to be a circular bullet hell like an artifact reliquary, but I just had no idea where the projectiles were and on hit with a surface/entity they snapfreeze around it?
