### ISSUE TITLE
Timely Execution challenge impossible?

### ISSUE THREAD

**Issue by Darkmega18** [TheMysticSword/MysticsItems#282]
I've been trying for a little bit to give a saw to an equipment drone and then get hit by it ingame, which I can only guess is how to do the achievement for timely execution.
However I'm having an issue where the saws thrown by the drone don't seem to do anything to me.

I'm unsure if theres a mod in my midst that is stopping ally projectiles from doing direct damage except on AoE but cause the saws don't have any AoE I can't get damaged by them. So I'm unsure how to proceed.

**Comment by gaforb** [comment]
There's an artifact that allows friendly damage, which would allow a friendly equip drone sawmerang to kill you. There's also the (slim) chance that a scavenger spawns with one

**Comment by Darkmega18** [comment]
I know. I was USING chaos. but even with chaos, none of my drones could kill me. even when turning off better drones so I could strike them directly. the saws would just fly through me while it went to shoot other things.

even after installing a literal CHAOS mod that was meant make chaos even more chaosy the drone of my own couldn't hurt me.

**Comment by TheMysticSword** [comment]
Kind of fixed in 2.1.7, by removing the achievement. Too specific, and too buggy, it seems
