### ISSUE TITLE
[Suggestion/Balancing] Supply drop chests should appear more frequently.

### ISSUE THREAD

**Issue by Coffe-e** [TheMysticSword/MysticsItems#29]
It seems a bit excessive to have white-item equivalents take 10 minutes to obtain. and if the rarity-spread is anything like Tier 1 chests, i'd definitely have them appear at least every 6-7, one every 2 stages, or something along those lines.

**Comment by TheMysticSword** [comment]
Would bumping up the amount of items per player solve the issue? The functionality is already there so I can just make it drop, say, 3 items for each player in the lobby, and not make any additional code changes.
