### ISSUE TITLE
Wireless Voltmeter shield

### ISSUE THREAD

**Issue by AmbassadorPineapple** [TheMysticSword/MysticsItems#290]
The Shield aspect of Wireless Voltmeter does not function. No shield is ever granted, and because of this, I'm not sure the rest of the item works either.

**Comment by TheMysticSword** [comment]
This is an issue with the current version of Bubbet's Items that affects almost all shield-giving modded items. You can confirm that by getting the Echo-Voltaic Plankton from the Supply Drop mod, and having only Bubbet's Items as the other mod.
