### ISSUE TITLE
Unable to troubleshoot issue with chests not dropping items

### ISSUE THREAD

**Issue by Jendraj2** [TheMysticSword/MysticsItems#292]
If this appears to be the error message as a result of a mod config that is understandable, I'd like to know if there's a particular type of thing I might need to disable to be able to fix this

Multishops drop their items just fine, but chests cant drop items. Are there any large content mods with known conflicts? I was simply opening chests, I did not have this active, I disabled it via config, and used content disabler, however this message involving the active still came up.

[Error  : Unity Log] MissingMethodException: void RoR2.PickupDropletController.CreatePickupDroplet(RoR2.GenericPickupController/CreatePickupInfo,UnityEngine.Vector3,UnityEngine.Vector3)
Stack trace:
DMD<>?865997568.Hook<RoR2.ChestBehavior::ItemDrop>?1647336448 (RoR2.ChestBehavior ) (at <5aec0ae198c44d96939f2d2c86305f6f>:IL_000A)
DMD<>?865997568.Trampoline<RoR2.ChestBehavior::ItemDrop>?-597661696 (RoR2.ChestBehavior ) (at <da86ff78a00b47a48189eeb064b7f1f3>:IL_0020)
MysticsItems.Equipment.OmarHackTool.ChestBehavior_ItemDrop (On.RoR2.ChestBehavior+orig_ItemDrop orig, RoR2.ChestBehavior self) (at <ffbb136a32284f3bac34b6df69677164>:IL_0040)
DMD<>?865997568.Hook<RoR2.ChestBehavior::ItemDrop>?1184550016 (RoR2.ChestBehavior ) (at <0c81f93a51d742d79e2dca4e3f0320d2>:IL_0014)
RoR2.AnimationEvents.ItemDrop () (at <78ca0507428e4dbea7a28fe14402f720>:IL_0032)

**Comment by TheMysticSword** [comment]
Could you try installing the GoxOfBears mod by pseudopulse and see if that fixes the issue?
https://thunderstore.io/package/pseudopulse/GoxOfBears/
