### ISSUE TITLE
Incompatibility with better UI mod

### ISSUE THREAD

**Issue by Lucalaure** [TheMysticSword/MysticsItems#44]
There seems to be an issue regarding the item descriptions when using the better UI mod. 
Also compatibility with item stats would be a godsend!

**Comment by TheMysticSword** [comment]
What is the issue, exactly? The descriptions work fine for me
![image](https://user-images.githubusercontent.com/26709843/111661977-55408980-8831-11eb-9978-ca49d9d4ace1.png)

**Comment by Lucalaure** [comment]
You're right. I assumed it was considering it was the only mod I use that changes UI but after some testing I can confirm that's not the one causing the issues. 
![ror2 bug](https://user-images.githubusercontent.com/66835898/111666418-163b1580-87ea-11eb-86db-eac6defa19d6.png)

This is what the bug looks like for me and these are the mods I use:
![Capture](https://user-images.githubusercontent.com/66835898/111666680-53070c80-87ea-11eb-81e1-281980a871fc.PNG)

I would do the testing myself but I don't have time atm. I also have other mods that add items such as atherium and supply drop and they work completely fine.

**Comment by TheMysticSword** [comment]
Oh, you're missing the MysticsItems.language file from the archive. You should put it in the folder with the dlls
