### ISSUE TITLE
Shrine of Legends Bug

### ISSUE THREAD

**Issue by 87527z** [TheMysticSword/MysticsItems#51]
Cant jump after hitting it, its intermittent on whether i can jump or not, it also just cancels momentum sometimes.
I Have a clip to show everything that happened including the items that i had, the items that it took, and what i got.
https://lowkey.gg/v/c2366796-6ad4-4892-9e29-6f27e7cd34c3

**Comment by TheMysticSword** [comment]
Could you please share your profile with me? I tried to replicate the bug with the items from the video but it didn't happen, so I must be missing a mod that causes this behaviour.

**Comment by 87527z** [comment]
Sorry for the late reply, I work overnights so I sleep during the day, when I get home I’ll send you the mod profile and anything else you need

**Comment by 87527z** [comment]
Code for the mod profile
G0CmsFKBVx

**Comment by TheMysticSword** [comment]
Oh, that's not a bug with this mod. Apparently that's what "The Oddity" does, from LargeSpanish's ExtraItems https://thunderstore.io/package/LargeSpanish/ExtraItems/0.1.0/

**Comment by 87527z** [comment]
Sorry for the misunderstanding.
