### ISSUE TITLE
"Wireless Voltmeter" changes

### ISSUE THREAD

**Issue by spindocks** [TheMysticSword/MysticsItems#6]
Without shield, Wireless Voltmeter doesn't do anything. I think it should grant 4% shield upon first pickup so that it will at the very least do something. Furthermore, I think that it should have a 0 proc coefficient, so that it is unable to proc bands.

**Comment by TheMysticSword** [comment]
It does give 4% shield on the first pickup though. I'll add that to the logbook description in the next patch. And, yeah, I'll remove the proc coefficient, totally forgot about it being able to proc bands out of your control!

**Comment by TheMysticSword** [comment]
Fixed with dc08105c0d48f7f60901519a4da9b8e9b5648c1f and da0602bb8e427a762b08399ac79ed216200fd67b respectively
