### ISSUE TITLE
Treasure Map Balancing

### ISSUE THREAD

**Issue by Azzezima** [TheMysticSword/MysticsItems#7]
Because the treasure map area doesn't decay, I feel it's too strong of an item.
If it had a cap on the amount of time you can gain money from the area, it'd be more balanced.
You could change the stacking into adding more time to the cap.

So:
Gain access to a special spot on the map that grants gold over time for x seconds.
+x seconds per stack.

**Comment by TheMysticSword** [comment]
Maybe it should be like a mini-teleporter zone that you need to stand in for X seconds (-Y seconds per stack) to capture and get Z amount of money, once per stage?

**Comment by Azzezima** [comment]
"Maybe it should be like a mini-teleporter zone that you need to stand in for X seconds (-Y seconds per stack) to capture and get Z amount of money, once per stage?"
That's honestly way better. Fits the whole 'treasure' theme of it too, as if you're looking for it while in the zone.
With the way it is now i feel like it'd either be too slow or too fast.

**Comment by spindocks** [comment]
If it doesn't change mechanically, at lease keep it from making a zone in areas where time does not move, since you shouldn't be able to grind exp.

**Comment by TheMysticSword** [comment]
Done!
![image](https://user-images.githubusercontent.com/26709843/110653315-f3ec3b00-81de-11eb-9a70-b19232d3a23f.png)
![image](https://user-images.githubusercontent.com/26709843/110653377-023a5700-81df-11eb-81c8-c00f47858583.png)
