### ISSUE TITLE
Not working with EnigmaticThunder API

### ISSUE THREAD

**Issue by TheDankestJew** [TheMysticSword/MysticsItems#87]

**Comment by The-Noble** [comment]
It does, atleast it's working for me
Do you have MMhook as well?

**Comment by TheDankestJew** [comment]
Yes I do

**Comment by crowtalons** [comment]
I have the same problem. Either with just MMHOOK or MMHOOK and EnigmaticThunder enabled. No other mods, and the items are simply not present in the game, or the logbook.

**Comment by TheMysticSword** [comment]
Can you provide an error log? Maybe I can get this fixed in today's patch.

**Comment by TheDankestJew** [comment]
I will be able to send a log later today

**Comment by TheMysticSword** [comment]
EnigmaticThunderAPI is no longer used. Closing.
