### ISSUE TITLE
treasure chests appear for non-host players when no one has the treasure map

### ISSUE THREAD

**Issue by boopedbud** [TheMysticSword/MysticsItems#96]
I've noticed that when i play with my friend i can sometimes see the charge aura and the objective to unearth appears and other times it charges instantly when loading in but still can't be open unless you have the treasure map

**Comment by Inzanity99** [comment]
I can confirm, playing with my friend today and the client / non-host sees the chest, with price and 0% charge, but unable to charge. This happens seemingly random (not every stage), but as early as the first or second stage.
Host does not see the chest at all.
