### ISSUE TITLE
Logbook and command broken

### ISSUE THREAD

**Issue by TheArchivisst** [TheMysticSword/MysticsItems#98]
When opening up the logbook or white (specifically white) command essence, the screen becomes blank. I don't know if this is due to conflict with other mods, but the issue stopped when I disabled the mod.

![image](https://user-images.githubusercontent.com/81943300/113533279-8cd26400-959b-11eb-8517-7be61ea11183.png)

Edit: the issue with command essence no longer exists but the logbook entry issue does.
Edit: I believe the issue with command essence may be caused by a different mod, [https://thunderstore.io/package/Sivelos1/SivsItems/](url), as someone using that mod has reported that problem.

**Comment by SonOfGorkamorka** [comment]
to add more info this is most likely a mod conflict seeing as this happen with thinkinvis tiller mod and sivsitems when using this mod

**Comment by TheMysticSword** [comment]
Fixed!
